import { 
  Apple, 
  Banana, 
  Beef, 
  Carrot, 
  Coffee, 
  Cookie, 
  Egg, 
  Fish, 
  IceCream, 
  Milk, 
  Pizza, 
  Salad, 
  Search, 
  ShoppingCart, 
  User, 
  Home, 
  Heart, 
  Bell, 
  Mic, 
  Camera, 
  Clock, 
  MapPin, 
  CreditCard, 
  Settings, 
  LogOut, 
  ChevronRight, 
  ChevronLeft, 
  Star, 
  Plus, 
  Minus, 
  Trash2, 
  CheckCircle, 
  AlertCircle,
  TrendingUp, 
  Zap, 
  Smartphone, 
  LayoutDashboard, 
  Users, 
  Package, 
  Tag, 
  BarChart3,
  Flame,
  Dna,
  Scale,
  Calendar,
  Truck,
  ShieldCheck,
  Gift,
  Activity,
  Award,
  Phone,
  Video,
  Send,
  Moon,
  Globe,
  Edit,
  Briefcase,
  Store,
  AlertTriangle,
  ShoppingBag,
  Edit2,
  X
} from 'lucide-react';

export const CATEGORIES = [
  { id: 'fruits', name: 'Fruits', icon: Apple, color: 'bg-red-100 text-red-600' },
  { id: 'veg', name: 'Vegetables', icon: Carrot, color: 'bg-orange-100 text-orange-600' },
  { id: 'dairy', name: 'Dairy', icon: Milk, color: 'bg-blue-100 text-blue-600' },
  { id: 'snacks', name: 'Snacks', icon: Cookie, color: 'bg-yellow-100 text-yellow-600' },
  { id: 'meat', name: 'Meat', icon: Beef, color: 'bg-red-200 text-red-800' },
  { id: 'bakery', name: 'Bakery', icon: Pizza, color: 'bg-amber-100 text-amber-600' },
];

export const PRODUCTS = [
  {
    id: 1,
    name: 'Organic Bananas',
    price: 2.99,
    unit: '1kg',
    rating: 4.8,
    category: 'fruits',
    image: 'https://images.unsplash.com/photo-1603833665858-e61d17a86224?auto=format&fit=crop&q=80&w=400',
    calories: 89,
    protein: '1.1g',
    description: 'Fresh organic bananas sourced from local farms. Rich in potassium and perfect for a quick snack.'
  },
  {
    id: 2,
    name: 'Fresh Strawberries',
    price: 4.50,
    unit: '500g',
    rating: 4.9,
    category: 'fruits',
    image: 'https://images.unsplash.com/photo-1464960350293-9a8c33ad04bb?auto=format&fit=crop&q=80&w=400',
    calories: 33,
    protein: '0.7g',
    description: 'Sweet and juicy strawberries. Hand-picked at peak ripeness.'
  },
  {
    id: 3,
    name: 'Whole Milk',
    price: 1.80,
    unit: '1L',
    rating: 4.7,
    category: 'dairy',
    image: 'https://images.unsplash.com/photo-1563636619-e910f6401b9d?auto=format&fit=crop&q=80&w=400',
    calories: 146,
    protein: '8g',
    description: 'Fresh farm milk, pasteurized and homogenized. Rich in calcium.'
  },
  {
    id: 4,
    name: 'Avocado',
    price: 1.50,
    unit: '1pc',
    rating: 4.6,
    category: 'veg',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&q=80&w=400',
    calories: 160,
    protein: '2g',
    description: 'Creamy Hass avocado. Perfect for toast or salads.'
  },
  {
    id: 5,
    name: 'Sourdough Bread',
    price: 3.20,
    unit: '400g',
    rating: 4.8,
    category: 'bakery',
    image: 'https://images.unsplash.com/photo-1585478259715-876acc5be8eb?auto=format&fit=crop&q=80&w=400',
    calories: 289,
    protein: '12g',
    description: 'Artisan sourdough bread baked fresh daily with natural yeast.'
  },
  {
    id: 6,
    name: 'Greek Yogurt',
    price: 2.50,
    unit: '200g',
    rating: 4.9,
    category: 'dairy',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=400',
    calories: 59,
    protein: '10g',
    description: 'Thick and creamy Greek yogurt. High in protein and probiotics.'
  }
];

export const ICONS = {
  Home,
  Search,
  ShoppingCart,
  User,
  Heart,
  Bell,
  Mic,
  Camera,
  Clock,
  MapPin,
  CreditCard,
  Settings,
  LogOut,
  ChevronRight,
  ChevronLeft,
  Star,
  Plus,
  Minus,
  Trash2,
  CheckCircle,
  AlertCircle,
  TrendingUp,
  Zap,
  Smartphone,
  LayoutDashboard,
  Users,
  Package,
  Tag,
  BarChart3,
  Flame,
  Dna,
  Scale,
  Calendar,
  Truck,
  ShieldCheck,
  Gift,
  Milk,
  Carrot,
  Apple,
  Activity,
  Award,
  Phone,
  Video,
  Send,
  Moon,
  Globe,
  Edit,
  Briefcase,
  Store,
  AlertTriangle,
  ShoppingBag,
  Edit2,
  X
};
